[build]
  command = "make all"
  functions = "api"
  publish = "site"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "github.com/bldulam1/aws-lambda-go-example"
